--------------------------------------------------------
--  File created - Středa-listopadu-08-2017   
--------------------------------------------------------
-- Unable to render TABLE DDL for object IT218.ODDEL with DBMS_METADATA attempting internal generator.
CREATE TABLE IT218.ODDEL 
(
  CIS_ODD NUMBER(*, 0) NOT NULL 
, NAZEV VARCHAR2(20 BYTE) NOT NULL 
, SEF NUMBER(*, 0) 
, CONSTRAINT PK_ODDEL PRIMARY KEY 
  (
    CIS_ODD 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE IT218.ODDEL
ADD CONSTRAINT FK_ODDEL_VEDE_ZAM FOREIGN KEY
(
  SEF 
)
REFERENCES IT218.ZAM
(
  OS_CIS 
)
ENABLECREATE UNIQUE INDEX IT218.PK_ODDEL ON IT218.ODDEL (CIS_ODD ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX IT218.VEDE_FK ON IT218.ODDEL (SEF ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
REM INSERTING into IT218.ODDEL
SET DEFINE OFF;
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('1','PROJEKCE','6');
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('2','KNIHOVNA','12');
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('3','PROGRAMOVANI','20');
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('4','BUFET','31');
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('6','SKLAD','41');
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('7','STB',null);
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('8','PROVOZ POCITACE','51');
Insert into IT218.ODDEL (CIS_ODD,NAZEV,SEF) values ('10','REDITELSTVI','77');
