--------------------------------------------------------
--  File created - Středa-listopadu-08-2017   
--------------------------------------------------------
-- Unable to render TABLE DDL for object IT218.ZAM with DBMS_METADATA attempting internal generator.
CREATE TABLE IT218.ZAM 
(
  OS_CIS NUMBER(*, 0) NOT NULL 
, JMENO VARCHAR2(25 BYTE) NOT NULL 
, FCE VARCHAR2(12 BYTE) 
, TITUL VARCHAR2(4 BYTE) 
, PLAT NUMBER(8, 2) NOT NULL 
, CIS_ODD NUMBER(*, 0) NOT NULL 
, NADR NUMBER(*, 0) 
, CONSTRAINT PK_ZAM PRIMARY KEY 
  (
    OS_CIS 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE IT218.ZAM
ADD CONSTRAINT FK_ZAM_NADRIZENO_ZAM FOREIGN KEY
(
  NADR 
)
REFERENCES IT218.ZAM
(
  OS_CIS 
)
ENABLE
ALTER TABLE IT218.ZAM
ADD CONSTRAINT FK_ZAM_ZARAZENI_ODDEL FOREIGN KEY
(
  CIS_ODD 
)
REFERENCES IT218.ODDEL
(
  CIS_ODD 
)
ENABLECREATE INDEX IT218.NADRIZENOST_FK ON IT218.ZAM (NADR ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX IT218.PK_ZAM ON IT218.ZAM (OS_CIS ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX IT218.ZARAZENI_FK ON IT218.ZAM (CIS_ODD ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
REM INSERTING into IT218.ZAM
SET DEFINE OFF;
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('1','KONADRA','POSLICEK',null,'5400','1','6');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('2','SYKORA','BESTBOY',null,'6000','1','6');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('3','STRNAD','SVACINAR',null,'7500','1','6');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('4','KOS','PROJEKTANT','ING','10500','1','6');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('5','KOS','PROJEKTANT','ING','10800','1','6');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('6','VOREL','BOSS','ING','12000','1','7');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('7','DATEL','BOSS','RNDR','12600','1','77');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('8','MALY','POSLICEK',null,'6000','2','11');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('9','DLOUHY','KNIHOVNIK',null,'9000','2','11');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('10','VYSOKY','KNIHOVNIK',null,'10500','2','11');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('11','TLUSTY','KNIHOVNIK','ING','11100','2','13');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('12','TLUSTY','SVACINAR',null,'6000','2','13');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('13','OTYLY','BOSS','ING','12000','2','14');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('14','OBROVSKY','BOSS','RNDR','13500','2','77');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('15','CERNY','PROGRAMATOR',null,'7500','3','21');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('16','CERVENY','PROGRAMATOR',null,'9000','3','21');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('17','ZELENY','PROGRAMATOR','ING','10500','3','21');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('18','ZELENY','PROGRAMATOR','ING','10500','3','21');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('19','FIALKA','PROGRAMATOR','ING','10500','3','21');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('20','FIALOVA','PROGRAMATOR','RNDR','10200','3','21');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('21','ZLATUSKA','BOSS','RNDR','13500','3','77');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('31','SEBESTOVA','BOSS',null,'8400','4','77');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('32','MACHOVA','BUFETACKA',null,'7500','4','31');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('33','HORACKOVA','UKLIZECKA',null,'7500','4','31');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('34','HORACKOVA','BUFETACKA',null,'7800','4','31');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('35','PAZOUTOVA','MYCKA NADOBI',null,'6600','4','31');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('36','KADRNOZKOVA','MYCKA NADOBI',null,'6600','4','31');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('37','JONATANOVA','UKLIZECKA',null,'6600','4','31');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('41','CECH','BOSS','ING','9000','6','77');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('42','SLOVAK','SKLADNIK',null,'6600','6','41');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('43','NEMEC','SKLADNIK',null,'7200','6','41');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('44','CECH','SKLADNIK',null,'7500','6','41');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('51','KOCOUR','BOSS','DOC','12900','8','77');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('52','KOCOUR','SEF TECHNIK','ING','11400','8','51');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('53','KOBYLKA','TECHNIK','ING','10500','8','52');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('54','KOCICKA','TECHNIK',null,'10200','8','52');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('55','PAPOUSEK','TECHNIK',null,'10200','8','52');
Insert into IT218.ZAM (OS_CIS,JMENO,FCE,TITUL,PLAT,CIS_ODD,NADR) values ('77','SEFICEK','REDITEL','DOC','15000','10',null);
